### PR TITLE
fix(Dockerfile): convert tabs to spaces

### PR DESCRIPTION
**Pull request by bacongobbler**
This commit converts all spacing to tabs and prefixes concatenated strings
with '&&' rather than suffixing the strings. This brings a more consistent
style to the Dockerfile.

### CODE REVIEW

**Comment by helgi** [comment]
I'm thumbs down on this since all other repos are `&&` at the end and use spaces.

**Comment by bacongobbler** [comment]
[We used this syntax before #145](https://github.com/deis/postgres/blob/v2.2.1/rootfs/Dockerfile).

Some popular community Docker images also use this style when chaining commands:

https://github.com/docker/docker/blob/master/Dockerfile#L89-L95
https://github.com/docker-library/postgres/blob/master/9.4/Dockerfile#L9-L19
https://github.com/docker-library/elasticsearch/blob/master/2.2/Dockerfile#L24-L27

Personally I'd rather follow community's best practices. It does look subjectively cleaner, in my opinion.

**Comment by bacongobbler** [comment]
As for spaces vs. tabs, same argument applies here. If we want to follow a consistent style then it's probably best to follow Docker's best practices, which in that case would be prefixed ampersands and tabs.

**Comment by helgi** [comment]
Well if you update this one then please update all other images. I'm not going to try to argue it against this change. I find the current style cleaner. A few community images isn't any more of a standard than if I pointed to numerous other Dockerfiles or shell scripts :)

**Comment by bacongobbler** [comment]
Sure, I'd be happy to go on a formatting crusade. I'll keep this out until I do the same to the rest of the Dockerfiles.

**Comment by bacongobbler** [comment]
And for what it's worth, it's not explicitly stated but https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run does demonstrate this syntax as well. Nothing is said about tabs/spaces so I can change that back if that's preferred. Just want to make it one or the other rather than mixing the two.

**Comment by helgi** [comment]
Pick a style you want and go with that if you are going over it all anyway

**Comment by mboersma** [comment]
Tabs cause more problems than they solve IMHO and I also find the suffixed `&&` style more readable. I also think we are inferring a best practice that isn't that pervasive, although I could be persuaded otherwise.

Having said that, I would like to see consistency among our Dockerfiles if possible, so if we can agree here we should do it everywhere. :hobgoblin:

**Comment by bacongobbler** [comment]
Alright if the rest of our components were using the suffixed style, let's use that. I've changed this PR to use spaces so I'll edit the PR to reflect that, and revert the changes to the poor ampersands

**Comment by krancour** [comment]
Fwiw, the `&&` at the end of the preceding lines vs the start of successive lines might have came mostly from me back when I was heavily refactoring all our components' Dockerfiles to transition from Alpine to Ubuntu slim, at which time I also made other optimizations to reduce image size (e.g. combining successive RUN directives with `&& \` to reduce the number of layers).

I'm glad @mboersma likes it the way I did it, but personally, and with hindsight being 20/20, I actually agree with @bacongobbler and wish I'd put the `&&` at the beginning of lines as I now find _that_ more readable. (The way my brain works changed? idk.)

All that being said, even being as big a fan of consistency as I am, it's probably not useful to obsess over keeping this (or tabs vs spaces) consistent from repo to repo. As long as we're consistent _within a single Dockerfile_, I think that's good enough. i.e. I wouldn't recommend the aforementioned formatting crusade. `</opinion>`

**Pull request merged**
