### PR TITLE
feat(charts): add backup to preStop hook

### LINKED ISSUE #164: perform backup on shutdown
Now backup is performed as background job. It would be nice to perform backup before shutdown, when a container gets TERM or INT signal.

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #164.

### CODE REVIEW

**Comment by bacongobbler** [comment]
@nailgun if you feel like taking a spin with this PR, please feel free to test it out.

**Comment by nailgun** [comment]
Ok, I will test this. But if I understand it in right way, `backup` [script](https://github.com/deis/postgres/blob/master/rootfs/bin/backup) will run infinite loop. Plus it sleeps before actually doing a backup.

**Comment by bacongobbler** [comment]
fixed.

**Comment by nailgun** [comment]
Great! Is there a simple way to inject this into my kubernetes? Or I need to build and store image somewhere?

**Comment by bacongobbler** [comment]
You can do so by running `kubectl --namespace=deis edit deployment deis-database`.

You'll have to modify the image being used to `quay.io/deisci/postgres:git-2615187` and add the preStop hook in there. Jenkins already created the image to test this PR.

Note that this image should only be used temporarily for testing purposes as we clean out the `deisci` org of all images occasionally.

**Comment by mboersma** [comment]
I tested this but it appears the script is run as root, not postgres, which causes a problem?
```shell
.82 seg=000000020000000000000010 state=complete
FATAL:  role "root" does not exist
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
```

**Comment by mboersma** [comment]
Also could you create a deis/charts PR for the workflow-dev chart to go with this? Some of us still test with Helm classic for a few things... 👴

**Comment by bacongobbler** [comment]
good catch @mboersma. The real invocation should be `gosu postgres do_backup`. I'll make that change here and PR a helm-classic change as well.

**Comment by mboersma** [comment]
I re-tested after this `gosu postgres` change and confirmed that killing a database pod kicks off the `preStop` backup process. Seems ok here in simple testing.

**Comment by nailgun** [comment]
Sorry for late reply. I broken my cluster :) Just rebuilt it (I'm new to kubernetes). @mboersma thanks for testing.

**Comment by bacongobbler** [comment]
closes #108

**Pull request merged**
