### PR TITLE
fix(001_setup_envdir.sh): inspect actual var instead of literal string

### PR DESCRIPTION
**Pull request by vdice**

### CODE REVIEW

**Comment by bacongobbler** [comment]
That would do it. cc @dmcnaught

**Comment by dmcnaught** [comment]
👍

**Comment by bacongobbler** [comment]
This also coincides with the story that it didn't work as of v2.9: https://github.com/deis/postgres/pull/167 was merged for v2.9.0.

closes #184

**Comment by vdice** [comment]
@dmcnaught I didn't realize this fix had broader implications -- does it happen to resolve some or all of the issues in https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+user%3Adeis+milestone%3Av2.11+author%3Admcnaught+ ?

**Comment by dmcnaught** [comment]
I think it should fix those 3 - my trail to the typo....

**Comment by bacongobbler** [comment]
yep! That was indeed the source of all of @dmcnaught's grief. Thanks for finding that!

**Comment by dmcnaught** [comment]
Can't believe I missed it :). Thanks

**Pull request merged**
